#!/usr/local/bin/php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>TABLE OF HAILSTONE SEQUENCE VALUES</title>
</head>
<body>
  <!-- Table that houses all the numbers from the hailstone sequence -->
  <table>
    <thead>
      <tr>
        <th>Iteration</th>
        <th>x</th>
      </tr>
    </thead>
    <tbody>
      <!-- This PHP generates the numbers that will fill up the table -->
      <?php 
        $x = $_GET['x']; //takes in variable from the URL
        $i = 0; //initialize variable that keeps track of iterations

        /* 
        Recursive function calculates and pushes values from the hailstone sequence into the table.
        Takes in number ($n) that will start the hail stone sequence and another number that keeps track of the iteration.
        */
        function hailstoneSequence($n, $iteration) {
          /* Breaks out of recursive function if value ($n) is equal to one*/
          if ($n === 1) {?>
            <tr> <td><?php echo $iteration?></td> <td><?php echo $n?></td> </tr> <!-- add last new values generated by this recursive function to table -->
            <?php
            return;
          }
          ?>
          <tr> <td><?php echo $iteration?></td> <td><?php echo $n?></td> </tr> <!-- add new values generated by this recursive function to table -->
          <?php
          $iteration++; //increase iteration value by 1 for every loop
          /* check to see if number passed in is even or odd*/
          if ($n % 2 === 0) {
            hailstoneSequence($n / 2, $iteration); //use recursive function again and pass in number and iterator
          } else {
            hailstoneSequence(3 * $n + 1, $iteration); //use recursive function again and pass in number and iterator
          }
        }
        hailstoneSequence($x, $i); //execute recursive function by passing in the number from url and iterator (starts at zero)
      ?>
    </tbody>
  </table>
</body>
</html>